# Generated by Django 4.2.1 on 2023-05-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название локации')),
                ('description_short', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Описание')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('imgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.placeimage', verbose_name='Картинки локации')),
            ],
        ),
    ]
