# Generated by Django 4.2.1 on 2023-06-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.placeimage', verbose_name='Картинки локации'),
        ),
    ]
