# Generated by Django 4.2.1 on 2023-07-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_slug_remove_placeimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='imgs',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', related_query_name='images', to='places.place', verbose_name='Локация'),
        ),
    ]
