# Generated by Django 4.2.1 on 2023-07-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Позиция'),
        ),
    ]
